service: edo-receipt-service

provider:
  name: aws
  runtime: python3.9
  stage: dev
  region: us-east-1
  memorySize: 512
  timeout: 60
  iam:
    role: arn:aws:iam::076456812464:role/LabRole
  environment:
    RECEIPTS_BUCKET: edo-receipts-${self:provider.stage}-fatima  # Adding name to ensure uniqueness
    ORDERS_TABLE: EdoOrdersTable

functions:
  generateReceipt:
    handler: handler.generate_receipt
    events:
      - stream:
          type: dynamodb
          arn: arn:aws:dynamodb:us-east-1:076456812464:table/EdoOrdersTable/stream/2025-11-30T04:26:45.585
          batchSize: 1
          startingPosition: LATEST
          filterPatterns:
            - eventName: [INSERT]

resources:
  Resources:
    ReceiptsBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: edo-receipts-${self:provider.stage}-fatima
        PublicAccessBlockConfiguration:
          BlockPublicAcls: false
          BlockPublicPolicy: false
        CorsConfiguration:
          CorsRules:
            - AllowedOrigins: ['*']
              AllowedMethods: [GET]
              AllowedHeaders: ['*']
    
    # Policy for public read access (optional, depending on requirements)
    ReceiptsBucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket: !Ref ReceiptsBucket
        PolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Sid: PublicReadGetObject
              Effect: Allow
              Principal: "*"
              Action: "s3:GetObject"
              Resource: !Join ['', ['arn:aws:s3:::', !Ref ReceiptsBucket, '/*']]
